name: Build uiconf
run-name: Build uiconf

on:
  workflow_call:
    secrets:
      CENTRAL_ACCOUNT_ID:
        required: true
      SERVICES_ACCOUNT_ID:
        required: true
      S3_BUCKET_DEPLOYMENT:
        required: true
    inputs:
      stage:
        description: "build for specific type - example: 'canary/beta/latest'"
        required: true
        type: string
      schema-type:
        description: "schema-type - example: 'playerV3Versions/playerV3OvpVersions'"
        required: true
        type: string
    outputs:
      version:
        description: "version - example: '1.00.000'"
        value: ${{ jobs.build-uiconf.outputs.version }}

jobs:
  build-uiconf:
    runs-on: [ ubuntu-latest ]
    permissions:
      id-token: write
      contents: read
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.CENTRAL_ACCOUNT_ID }}:role/central-oidc-github-actions
          role-session-name: githubAction
          aws-region: "eu-central-1"

      - name: Increase version and update ssm param
        id: version
        run: |
          # Assume role
          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
                      $(aws sts assume-role \
                      --role-arn arn:aws:iam::${{ secrets.SERVICES_ACCOUNT_ID }}:role/nvp1-deployment-role \
                      --role-session-name "nvp1-${{ github.run_id }}" \
                      --region "us-east-1" \
                      --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
                      --output text))

          if [ "${{ inputs.stage }}" = "canary" ]; then
            oldVersion=$(aws ssm get-parameters --names /player/versions/uiconf/canary --region us-east-1 | jq -r .Parameters[].Value)
            if [ "${oldVersion}" = "NULL" ]; then
              oldVersion=$(aws ssm get-parameters --names /player/versions/uiconf/latest --region us-east-1 | jq -r .Parameters[].Value)
              newVersion="${oldVersion}.001"
            else
              newVersion=$(echo "${oldVersion}" | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
            fi
          else
            oldVersion=$(aws ssm get-parameters --names /player/versions/uiconf/latest --region us-east-1 | jq -r .Parameters[].Value)
            newVersion=$(echo "${oldVersion}" | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
            if [ "${{ inputs.stage }}" = "latest" ]; then
              aws ssm put-parameter --name /player/versions/uiconf/canary-dor-test --value "NULL" --overwrite --region us-east-1
            fi
          fi

          aws ssm put-parameter --name /player/versions/uiconf/${{ inputs.stage }}-dor-test --value ${newVersion} --overwrite --region us-east-1

          echo "new version is: ${newVersion}"
          echo "version=${newVersion}" >> $GITHUB_OUTPUT

      - name: Build uiconf for ${{ inputs.stage }} on schema-type ${{ inputs.schema-type }}
        run: |
          # Assume role
          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
                      $(aws sts assume-role \
                      --role-arn arn:aws:iam::${{ secrets.SERVICES_ACCOUNT_ID }}:role/nvp1-deployment-role \
                      --role-session-name "nvp1-${{ github.run_id }}" \
                      --region "us-east-1" \
                      --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
                      --output text))

          jsonName="playkit_dor_test_${{ inputs.schema-type }}_${{ steps.version.outputs.version }}_${{ inputs.stage }}.json"

          s3Path="s3://nvp1-${{ secrets.S3_BUCKET_DEPLOYMENT }}/player/uiconf"

          tmp=$(mktemp)
          echo "[general]" > "$tmp"
          echo "component.name = ${{ inputs.schema-type }}" >> "$tmp"
          echo "component.version = ${{ inputs.stage }}" >> "$tmp"
          echo "\n" >> "$tmp"
          echo "[defaultKdp]" >> "$tmp"
          echo "objectType = 6" >> "$tmp"
          echo "widgets.versions.conf_vars = '{"version":"${{ steps.version.outputs.version }}"}'" >> "$tmp"
          echo "widgets.versions.name = playkitVersions" >> "$tmp"
          echo "widgets.versions.usage = list,${{ steps.version.outputs.version }},${{ inputs.schema-type }},${{ inputs.stage }}" >> "$tmp"
          echo "widgets.versions.config = '${jsonConf}'" >> "$tmp"

          mv "$tmp" ${jsonName}

          aws s3 cp ${jsonName} ${s3Path}/


