## CI/CD
name: Canary Full Flow
run-name: Canary Full Flow

on:
  push:
    branches:
      - devops-deployment

jobs:
  canary-full-flow:
    uses: kaltura/ovp-pipelines-pub/.github/workflows/player_cicd.yaml@master
    secrets:
      CENTRAL_ACCOUNT_ID: ${{ secrets.CENTRAL_ACCOUNT_ID }}
      SERVICES_ACCOUNT_ID: ${{ secrets.SERVICES_ACCOUNT_ID }}
      S3_BUCKET_DEPLOYMENT: ${{ secrets.S3_BUCKET_DEPLOYMENT }}
      S3_BUCKET_APPS: ${{ secrets.S3_BUCKET_APPS }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
      LAMBDA_NAME: ${{ secrets.LAMBDA_NAME }}
      MSTEAMS_WEBHOOK: ${{ secrets.MSTEAMS_WEBHOOK }}
    with:
      type: "plugin"
      stage: "canary"
      schema-type: "playerV3Versions"
      tests-yarn-run-to-execute: 'eslint flow test'

