## CI - Upload packages to NPM
name: Upload packages to NPM and S3
run-name: Upload packages to NPM and S3

on:
  push:
    branches:
      - devops-pr

jobs:
  running-tests:
    uses: ./.github/workflows/tests.yaml
    with:
      yarn-run-to-execute: 'eslint flow'
  upload-packages-to-npm:
    needs: running-tests
    uses: ./.github/workflows/upload_to_npm.yaml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      prod: "false"
  upload-to-s3-qa-and-dev:
    needs: upload-packages-to-npm
    uses: ./.github/workflows/upload_to_s3.yaml
    secrets:
      CENTRAL_ACCOUNT_ID: ${{ secrets.CENTRAL_ACCOUNT_ID }}
      S3_BUCKET_APPS: ${{ secrets.S3_BUCKET_APPS }}
    with:
      aws-secret-central: '"dor-test-github-actions-Q3jQq1"'
      kind: "plugin"
      name: ${{ needs.upload-packages-to-npm.outputs.name }}
      version: ${{ needs.upload-packages-to-npm.outputs.version }}
      full-npm-name: ${{ needs.upload-packages-to-npm.outputs.full-npm-name }}
