## CI - Player And Plugin Tests
name: Player And Plugin Tests
run-name: Player And Plugin Tests

on:
  push:
    branches:
      - devops-deployment

jobs:
  running-tests:
    uses: kaltura/ovp-pipelines-pub/.github/workflows/player_tests.yaml@master
    with:
      yarn-run-to-execute: 'eslint flow test'


